biquge/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("fiction/", include("fiction.urls")),
    # path("chapter/", include("fiction.urls")),
    path("admin/", admin.site.urls),
]

fiction/urls.py
from django.urls import path

from . import views


app_name = "fiction"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:fiction_code>/", views.detail, name="detail"),
    path("chapter/<str:chapter_code>/", views.chapter_detail, name="chapter_detail"),
]

fiction/models.py
from django.db import models


# Create your models here.
class FictionList(models.Model):
    fiction_code = models.TextField()
    fiction_name = models.TextField()
    fiction_info = models.TextField()
    fiction_introduce = models.TextField()
    fiction_author = models.TextField()
    fiction_type = models.TextField()
    fiction_image_url = models.TextField()
    fiction_count = models.TextField()
    create_time = models.DateTimeField()
    update_time = models.DateTimeField()


class ChapterList(models.Model):
    fiction_code = models.TextField()
    chapter_code = models.TextField()
    chapter_name = models.TextField()
    chapter_order = models.IntegerField()
    create_time = models.DateTimeField()
    update_time = models.DateTimeField()


class ChapterDetailList(models.Model):
    chapter_code = models.TextField()
    chapter_content = models.TextField()

fiction/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.template import loader
from django.views import generic

from .models import FictionList, ChapterList, ChapterDetailList
import json
import re


def index(request):
    data_list = FictionList.objects.all()[:12]
    context = {
        "data_list": data_list,
    }
    return render(request, "fiction/index.html", context)


def detail(request, fiction_code):
    fiction_data = get_object_or_404(FictionList, fiction_code=fiction_code)
    chapter_list = get_list_or_404(ChapterList.objects.order_by('chapter_order'), fiction_code=fiction_code)
    context = {
        "fiction_code": fiction_code,
        "fiction_data": fiction_data,
        "chapter_list": chapter_list,
    }
    return render(request, "fiction/detail.html", context)


def chapter_detail(request, chapter_code):
    chapter_info = get_object_or_404(ChapterList, chapter_code=chapter_code)
    chapter_data = get_object_or_404(ChapterDetailList, chapter_code=chapter_code)
    chapter_data_list = json.loads(chapter_data.chapter_content)
    context = {
        "chapter_info": chapter_info,
        "chapter_data_list": chapter_data_list,
    }
    return render(request, "fiction/chapter_detail.html", context)

fiction/templates/fiction/chapter_detail.html
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'fiction/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'fiction/style.css' %}">
    <title>{{ chapter_info.chapter_name }}</title>
</head>
<body class="container">
<div style="margin: 30px;"></div>
<h1 class="title">{{ chapter_info.chapter_name }}</h1>

<div class="box">
{% if chapter_data_list %}
    {% for each_content in chapter_data_list %}
    <div class="block">
        {{ each_content }}
    </div>
    {% endfor %}
{% else %}
    <p>No Data.</p>
{% endif %}
</div>
</body>
</html>

fiction/templates/fiction/detail.html
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'fiction/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'fiction/style.css' %}">
    <title>{{ fiction_data.fiction_name }}</title>
</head>
<body class="container">
<div style="margin: 30px;"></div>
<div class="box">
    <div class="fiction-detail-info-box">
       <div class="detail-image-box">
           <img src="{{ fiction_data.fiction_image_url }}" alt="">
       </div>
       <div class="title-box">
           {{ fiction_data.fiction_name }}
       </div>
       <div class="author-box">
           <span class="tag is-primary is-light">{{ fiction_data.fiction_author }}</span>
           |
           <span class="tag is-success is-light">{{ fiction_data.fiction_type }}</span>
       </div>
       <div class="introduce-box">
           {{ fiction_data.fiction_introduce }}
       </div>
        <div class="other-info-box">
            {{ fiction_data.fiction_info }}
        </div>
    </div>
</div>
{%if chapter_list %}
<div class="fixed-grid has-4-cols">
    <div class="grid">
    {% for each_chapter in chapter_list %}
      <a href="{% url 'fiction:chapter_detail' each_chapter.chapter_code %}" target="_blank">
          <div class="cell">
              <div class="box">
                  {{ each_chapter.chapter_name }}
              </div>
          </div>
      </a>
    {% endfor %}
    </div>
</div>
{% else %}
<p>No Data.</p>
{% endif %}
</body>
</html>